### ISSUE TITLE
Student view of his/her own result at third phase

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#102]
### Description

As a student consulting the results of a sequence
I want to see my answer, my score, and my mean grade obtained on my argumentation
So that I can get a personnalised feedback on the sequence

### Acceptation tests

Given a student consulting the results of a sequence
Then a block is displayed on the top of the results containing:
- the student's choice and the calculated score (between 0 and 100) at the first vote if relevant
- the student's explanation and the mean grade obtained after the peer rating phase
- the student's choice and the calculated score (between 0 and 100) at the second vote if relevant

## Hint
A prototype should be provided before coding

**Comment by EmmaMauger** [comment]
Questions : 
A-t-on accès à ces informations lors de toutes les phases d'une séquence, ou est-ce un résumé final ?

**Comment by FranckSilvestre** [comment]
Ces informations ne doivent être visibles qu'à la phase de restitution.
