### ISSUE TITLE
Development of a prototype to establish a comprehensible hierarchy between courses and subjects

### ISSUE THREAD

**Issue by EmmaMauger** [elaastic/elaastic-questions-server#114]
The courses and subjects are displayed in the same way so with the current interface it's difficult for a new user to differentiate these two concepts and their hierarchical dependency. 

We need to adapt the current interface to differentiate courses and subjects and to show that courses contain subjects.

Different prototypes are required for illustrate the following ideas : 
- "Copy" the left side bar like in Evernote
- Use icons in front of a course and subject titles (a folder icon for a course and a document icon for the subject)
- Use labels to show information at the right of a course title 

The bullets 2 and 3 could be used together

### Evernote
![469487864_ScreenShot2019-12-05at11_33_44am png 17c9e551d9bf8fc13ccf63d72b9130c2](https://user-images.githubusercontent.com/38081700/112363866-41d06b00-8cd6-11eb-9695-66163a687366.png)

**Comment by FranckSilvestre** [comment]
Some present problems on the current interface...
### Left hand side
- the background of the button representing the current location in the application is not different from the other : no feedback given to the user on his/her position in the application
- we have to mouse over the buttons to know what they represent : signifier comes to late.
- the order of buttons is confusing.
