### ISSUE TITLE
Creating a newly subject from a course must link it to the course and the field "Assigned course" from the creation popup should be set to the course name

### ISSUE THREAD

**Issue by EmmaMauger** [elaastic/elaastic-questions-server#115]
### Description

As a teacher
I want to access a course
So that I can create a subject associated with this course

### Acceptance Tests

>GIVEN

A teacher on a course page

>WHEN

He clicks on the "Create subject" button

>THEN

A pop-up appears for him to fill in the fields required, and the "Assigned course" field must already be set at the course name from which he created the subject

**Comment by BrunoPicolo** [comment]
Est-ce que le champ "Assigned course" doit être modifiable lors dans ce cas précis ? @FranckSilvestre

**Comment by FranckSilvestre** [comment]
> Est-ce que le champ "Assigned course" doit être modifiable dans ce cas précis ? @FranckSilvestre

Oui.
