### ISSUE TITLE
Visualisation of indicators on a sequence by a teacher

### ISSUE THREAD

**Issue by QuentinChampeau** [elaastic/elaastic-questions-server#16]
### Description
As a teacher
I want to be able to see the indicators of the question in a third tab in the stats page
So that I can easily understand how well the question had been understood.

![Onglet 3.PNG](https://images.zenhubusercontent.com/5ae610b24b5806bc2bd11289/62ec3c5b-9f72-4629-94d6-5bf052211c7b)

**Comment by AlexisMat** [comment]
Le squelette de chaque onglet est visible en plus des informations du troisième onglet

**Comment by FranckSilvestre** [comment]
Technical hint : reuse the components already written for the player to display the results as is.
