### ISSUE TITLE
Teacher is notified during a sequence when an evaluation is reported

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#172]
### Description

As a teacher connected to the A sequence,
I want to be notified when a student reported an evaluation in the A sequence
So that I can quickly react to the situation  

### Acceptance criteria

- [ ] The teacher is notified directly during the sequence (s)he is connected to inside the elaastic interface.

**Comment by Francois389** [comment]
# Design

![Image](https://github.com/user-attachments/assets/c14e8ab7-7d22-4d74-8aab-530e6bb42989)
