### ISSUE TITLE
A student can evaluate an answer using the DRAXO dynamic grid

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#173]
### Description

As a student participating in the second phase of an Elaastic sequence
I want to evaluate the answers that are proposed to me using the DRAXO dynamic criteria grid
So that each student receive an enriched feedback for his/her answer.

### Acceptance Criteria

- [x] The DRAXO form conforms to the detail specification provided as attachment
- [ ] A link with the detailed explanation of the DRAXO grid is available by students who consult their evaluations 

[PresentationDRAXO.pdf](https://github.com/elaastic/elaastic-questions-server/files/11432432/PresentationDRAXO.pdf)

**Comment by jtranier** [comment]
The link to the detailed explanation of the DRAXO grid has to be set through elaastic.draxo.help.url config property.

If not defined, the link won't be shown.
