### ISSUE TITLE
NeXT - New package structure proposal

### ISSUE THREAD

**Issue by jtranier** [elaastic/elaastic-questions-server#274]
### Drives
- Prepare the microservices migration (i.e. the monolith application can be easily split into microservice according to the 1st level packages)
- Being natural so that new contributors can easily get the logics

**Comment by Francois389** [comment]
## New Arborescence

```mermaid
---
title: Packages
---
graph LR
org --> elaastic
  elaastic --> consolidation
  elaastic --> assignment
  elaastic --> sequence
	  sequence --> config
	  sequence --> phase
	  sequence --> interaction
  elaastic --> common
	  common --> web
	  common --> abtesting --> feature
	  common --> util
  	common --> onboarding
  	common --> persistence
  elaastic --> analytics --> lrs
  elaastic --> material --> instructional
	  instructional --> course
	  instructional --> subject
	  instructional --> statement
	  instructional --> question --> explanation
		  question --> choice
		  question --> attachement
	elaastic --> filestore
  elaastic --> bootstrap
  elaastic --> user
	  user --> email
	  user --> legal
  elaastic --> auth
	  auth --> lti
	  auth --> cas
	  auth --> native
	elaastic --> security
	elaastic --> migration
	elaastic --> player
		player --> websocket
		player --> assignementview
		player --> command
		player --> chart
			chart --> confidence
			chart --> chart_evaluation[evaluation]
			chart --> chart_response[response]
		player --> dashboard
		player --> player_evaluation[evaluation]
			player_evaluation --> player_chatgpt[chatgpt]
			player_evaluation --> draxo
		player --> explanations
		player --> recommendation
		player --> player_response[response]
		player --> results --> learner
		player --> player_sequence[sequence] --> status
		player --> player_statement[statement]
		player --> steps
	elaastic --> ai
		ai --> ai_evaluation[evaluation] --> chatgpt
	elaastic --> activity
		activity --> response
		activity --> result
		activity --> evaluation --> peergrading
	elaastic --> moderation	
```

## Mapping with existing arborescence

- [ ] consolidation ← api.practice.*,
- [ ] assignment ← Assignment*.kt, LearnerAssingment*.kt, RevisionMode (à renommer en ReadyForConsolidation ou qqchose comme cela).
- [ ] common.web ← RestControllerAdvice, les classes du package “controller”
- [ ] common.abtesting ← le package “features”
- [ ] analytics.lrs ← eventLog.*
- [ ] sequence ← Sequence*, *Sequence*, ExecutionContext, 
- [ ] sequence.phase = player.phase 
- [ ] sequence.config ← config, assignment.sequence.interaction.specification
- [ ] sequence.interaction = assignment.sequence.interaction
- [ ] material.instructional ← packages course, subject (hors statement package), statement, question (← package “choice”, QuestionType.kt), attachment (to be refactored) 
- [ ] material.instructional.question.explanation = sequence.explanation, ← TeacherExplanation
- [ ] filestore ← package datastore
- [ ] bootstrap = bootstrap
- [ ] user ← directory
- [ ] user.email = email
- [ ] auth ← package “lti”, “directory.cas”, contenu de “security” à ventiler dans les packages “lti”, “cas”, “native”
- [ ] security ← security.*SecurityConfig
- [ ] migration = migration
- [ ] common.onboarding = onboarding 
- [ ] common.persistence = persistence 
- [ ] common.utils = utils
- [ ] player ← Player*, TestingPlayerController à renommer  en ComponentTestingController
- [ ] player.websocket = player.websocket
- [ ] player.assignmentview = player.component.assignmentOverview
- [ ] player.command = player.component.command
- [ ] player.chart ← packages “*DistributionChart” à renommer en “confidence” “evaluation” et “response”.
- [ ] player.dashboard = player.components.dashboard
- [ ] player.evaluation.chatgpt = player.components.chatGPTEvaluation
- [ ] player.evaluation.draxo = player.components.draxo
- [ ] player.evaluation ← EvaluationModel
- [ ] player.explanations = player.components.explanationViewer, ← ExplanationViewerDsl à renommer en ExplanationsDsl
- [ ] player.recommendation = player.components.recommendation
- [ ] player.response = player.components.responsePhase
- [ ] player.results = player.components.results
- [ ] player.results.learner = player.components.studentResults
- [ ] player.sequence.status = player.components.sequenceInfo
- [ ] player.statement = player.components.statement
- [ ] player.steps = player.components.steps
- [ ] user.legal = terms
- [ ] ai.evaluation.chatgpt = assignment.sequence.interaction.chatGPTEvaluation
- [ ] activity.response = assignment.sequence.interaction.response, ← ConfidenceDegree
- [ ] activity.results = assignment.sequence.interaction.results, ← ResponseDistributionConverter
- [ ] activity.evaluation ← ExplanationRecommandationMapping à renommer en PeerEvaluationMapping, ExplanationRecommandationMappingConverter à renommer en PeerEvaluationMappingConverter
- [ ] activity.evaluation.peergrading = assignment.sequence.peergrading, ← assignment.ia.*
- [ ] moderation ← assignment.sequence.moderation.* , assignment.sequence.report.*, assignment.sequence.ReportReason, assignment.sequence.UtilityGrade
