### ISSUE TITLE
Visualisation of indicators on a sequence by a teacher

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#5]
### Description

As a teacher
I want to visualize indicators on a sequence
So that it is easier for me to know what to do with the corresponding question (eg. adapt its statement, drop it, reuse it as-is, etc.).

### Hints
Indicators we want in the visualisation :
- a recall of how was the sequence set (face to face ? number of evaluations asked in phase 2, etc.)
- the distribution of students point of views on the sequence (to evaluate the "perceived usability of a sequence")
- ~~the trend of good answers between the 2 votes if the corresponding question is a choice question (to evaluate the "clarity of the question")~~
- the average confidence of the student and the distribution
- ~~success rate at first and second vote in case of choice question (to evaluate "difficulty" of the question)~~
- mean time spent by students to answer the question on first attempt
- mean time spent by students on phase 2
- participation rate on phase 1 and phase 2
- the average standard deviation of the grades of all the answers

![image](https://user-images.githubusercontent.com/17876275/76009417-762d8980-5f11-11ea-9747-a53f2bf72e12.png)

**low and medium level prototype needeed**

**Comment by AlexisMat** [comment]
Correspond au premier onglet de la page de statistique
