### ISSUE TITLE
Ask the user to rename a duplicated subject on the fly

### ISSUE THREAD

**Issue by Rialy** [elaastic/elaastic-questions-server#69]
To rename a duplicated subject, the user has to edit the duplicate's property. In Elaastic's previous version, the new name was asked to the user on the fly during the duplication.
Also, in the previous version, there was automatic redirection to the duplicate's edition page

**Comment by FranckSilvestre** [comment]
Currently, the title of the subject can be modified only through a modal window, and it is not really compliant with the automatic trigger of the popup while the page displays success message.
