### ISSUE TITLE
Display of students' rationals are anonymous for students

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#80]
### Description

As a student consulting the results of a sequence
I cannot know the identity of the authors of explanations
So that anonymity between students is preserved during all the process  

### Acceptation tests

Given a student consulting the results of a given sequence
Then neither the login, neither the name/first name/full name of the author of an explanation is displayed except mine

**Comment by EmmaMauger** [comment]
Questions : 
Quid du pseudo d'un étudiant ?
Comment se place cette US par rapport à la 81 ?

**Comment by FranckSilvestre** [comment]
Cette US ne concerne que l'interface étudiant alors que la #81 concerne l'interface enseignant.
Durant la phase 3 (restitution) ni les pseudos, ni les noms ne doivent être visibles pour les étudiants.
