### ISSUE TITLE
Name and first name  of students  are displayed for the teacher during all phases of a sequence

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#81]
### Description

As a teacher owner of a sequence
I want to know the identity of the author of an answer at each phase of the sequence
So that I can follow the production of each student nominatively

### Acceptation tests

Given a teacher orchestrating a sequence 
When,  whatever the phase and its state, some answers are displayed
Then, for each displayed explanation, the full name (first name + name) and the login are displayed in place of the current display of the login.

**Comment by EmmaMauger** [comment]
Questions : 
Où seront cachées ces informations ? Lors d'une séquence, dans les options de lancement ?

**Comment by FranckSilvestre** [comment]
Sur chaque phase d'une séquence, l'enseignant dispose d'une interface (switch button, case à cocher) permettant de basculer de l'état "Noms visibles"  l'état "Noms cachés".
Par défaut l'enseignant se trouve dans l'état où les noms sont visibles. C'est approximativement l'état actuel.  Dans l'état où les noms sont visibles, pour chaque contribution on affichera le "full name" (concaténation du  prénom et du nom) suivi du login entre parenthèses.
